"""Applies validated CSV records to the database inside a single transaction."""

from __future__ import annotations

import hashlib
import logging
import uuid
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal

from sqlalchemy import and_, select, tuple_
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from app.core.errors import NotFoundError, ValidationFailedError
from app.models import (
    Benchmark,
    BenchmarkObservation,
    DataSource,
    Fund,
    FundAum,
    FundHolding,
    FundSipFlow,
    ImportBatch,
    NavObservation,
)
from app.services.ingestion import validation
from app.services.ingestion.validation import MAX_REJECTED_ROWS_STORED, ParsedFile

logger = logging.getLogger("finsense.ingestion")

DEFAULT_SOURCES = {
    "synthetic-demo": ("FinSense synthetic demonstration data", "synthetic", True,
                       "Generated by sample_data/generate_sample_data.py. Fictional funds and values."),
    "csv-import": ("User-provided CSV import", "csv_import", False,
                   "Uploaded by an administrator. Provenance is the uploaded file."),
    "amfi": ("AMFI daily NAV file", "amfi", False,
             "Latest NAV published by the Association of Mutual Funds in India (NAVAll.txt)."),
}


def ensure_default_sources(db: Session) -> None:
    for code, (name, kind, synthetic, description) in DEFAULT_SOURCES.items():
        if db.scalar(select(DataSource.id).where(DataSource.code == code)) is None:
            db.add(DataSource(code=code, name=name, kind=kind, is_synthetic=synthetic, description=description))
    db.commit()


def get_source(db: Session, code: str) -> DataSource:
    source = db.scalar(select(DataSource).where(DataSource.code == code))
    if source is None:
        raise NotFoundError(f"Data source '{code}' does not exist.")
    return source


def import_csv(
    db: Session, *, kind: str, filename: str, content: bytes, source_code: str,
    uploaded_by: uuid.UUID | None, max_bytes: int, today: date | None = None,
) -> ImportBatch:
    text = validation.decode_csv_bytes(content, max_bytes=max_bytes)
    parsed = validation.parse_csv(kind, text, today=today)
    source = get_source(db, source_code)
    digest = hashlib.sha256(content).hexdigest()

    previous = db.scalar(
        select(ImportBatch).where(ImportBatch.content_sha256 == digest, ImportBatch.kind == kind,
                                  ImportBatch.status == "completed").order_by(ImportBatch.started_at.desc())
    )
    if previous is not None:
        parsed.warnings.append(
            f"An identical file was already imported on {previous.started_at:%Y-%m-%d %H:%M} UTC; "
            "re-importing is safe (existing rows are left unchanged)."
        )

    batch = ImportBatch(
        id=uuid.uuid4(), kind=kind, filename=filename[:255], content_sha256=digest, uploaded_by=uploaded_by,
        status="processing", rows_total=parsed.rows_total, warnings=[], rejected_rows=[],
    )
    try:
        db.add(batch)
        db.flush()
        handler = _HANDLERS[kind]
        inserted, updated, unchanged = handler(db, parsed, source, batch.id)
        batch.rows_inserted, batch.rows_updated, batch.rows_unchanged = inserted, updated, unchanged
        batch.rows_rejected = len(parsed.rejected)
        batch.warnings = parsed.warnings[:200]
        batch.rejected_rows = _jsonable(parsed.rejected[:MAX_REJECTED_ROWS_STORED])
        batch.status = "completed"
        batch.finished_at = datetime.now(UTC)
        db.commit()
    except (SQLAlchemyError, ValidationFailedError) as exc:
        db.rollback()
        logger.warning("CSV import of %s failed: %s", kind, type(exc).__name__)
        failed = ImportBatch(
            id=uuid.uuid4(), kind=kind, filename=filename[:255], content_sha256=digest, uploaded_by=uploaded_by,
            status="failed", rows_total=parsed.rows_total, rows_rejected=parsed.rows_total,
            warnings=[str(exc) if isinstance(exc, ValidationFailedError) else "Database error while saving rows."],
            rejected_rows=[], finished_at=datetime.now(UTC),
        )
        db.add(failed)
        db.commit()
        return failed
    return batch


def _jsonable(rows: list[dict]) -> list[dict]:
    out = []
    for row in rows:
        out.append({"line": row["line"], "reason": row["reason"],
                    "values": {k: str(v)[:120] for k, v in (row.get("values") or {}).items()}})
    return out


def _lookup_funds(db: Session, codes: set[str]) -> dict[str, Fund]:
    if not codes:
        return {}
    return {f.scheme_code: f for f in db.scalars(select(Fund).where(Fund.scheme_code.in_(codes)))}


def _lookup_benchmarks(db: Session, codes: set[str]) -> dict[str, Benchmark]:
    if not codes:
        return {}
    return {b.code: b for b in db.scalars(select(Benchmark).where(Benchmark.code.in_(codes)))}


def _resolve_funds(db: Session, parsed: ParsedFile, source: DataSource) -> list[tuple[dict, Fund]]:
    """Matches records to funds and refuses to mix synthetic and real observations."""
    funds = _lookup_funds(db, {r["scheme_code"] for r in parsed.records})
    resolved = []
    for record in parsed.records:
        fund = funds.get(record["scheme_code"])
        if fund is None:
            parsed.reject(record["_line"], f"unknown scheme_code '{record['scheme_code']}' (import funds first)")
        elif fund.is_synthetic != source.is_synthetic:
            parsed.reject(record["_line"],
                          f"{fund.scheme_code} is {'synthetic' if fund.is_synthetic else 'real'} data; "
                          f"cannot add {'synthetic' if source.is_synthetic else 'real'} observations to it")
        else:
            resolved.append((record, fund))
    return resolved


def _count_changes(existing: dict, incoming: dict, value_fields: list[str]) -> tuple[list, int, int, int]:
    """Splits incoming rows into those to write plus insert/update/unchanged counts.

    ``existing`` maps key -> tuple of current values (in ``value_fields`` order).
    """
    to_write, inserted, updated, unchanged = [], 0, 0, 0
    for key, values in incoming.items():
        current = existing.get(key)
        if current is None:
            inserted += 1
            to_write.append(values)
        elif tuple(current) != tuple(values[f] for f in value_fields):
            updated += 1
            to_write.append(values)
        else:
            unchanged += 1
    return to_write, inserted, updated, unchanged


def _bulk_upsert(db: Session, model, rows: list[dict], conflict_cols: list[str]) -> None:  # type: ignore[no-untyped-def]
    for start in range(0, len(rows), 5000):
        chunk = rows[start:start + 5000]
        stmt = insert(model).values(chunk)
        update_cols = {c: stmt.excluded[c] for c in chunk[0] if c not in conflict_cols}
        db.execute(stmt.on_conflict_do_update(index_elements=conflict_cols, set_=update_cols))


def _import_benchmarks(db: Session, parsed: ParsedFile, source: DataSource, _batch: uuid.UUID):
    existing = _lookup_benchmarks(db, {r["benchmark_code"] for r in parsed.records})
    inserted = updated = unchanged = 0
    for record in parsed.records:
        bench = existing.get(record["benchmark_code"])
        if bench is None:
            db.add(Benchmark(code=record["benchmark_code"], name=record["name"],
                             return_basis=record["return_basis"], source_id=source.id,
                             is_synthetic=source.is_synthetic))
            inserted += 1
        elif bench.is_synthetic != source.is_synthetic:
            parsed.reject(record["_line"], "cannot change a benchmark between synthetic and real data")
        elif (bench.name, bench.return_basis) != (record["name"], record["return_basis"]):
            bench.name, bench.return_basis = record["name"], record["return_basis"]
            updated += 1
        else:
            unchanged += 1
    return inserted, updated, unchanged


def _import_funds(db: Session, parsed: ParsedFile, source: DataSource, _batch: uuid.UUID):
    existing = _lookup_funds(db, {r["scheme_code"] for r in parsed.records})
    benchmarks = _lookup_benchmarks(db, {r["benchmark_code"] for r in parsed.records if r.get("benchmark_code")})
    inserted = updated = unchanged = 0
    for record in parsed.records:
        bench_code = record.get("benchmark_code")
        if bench_code and bench_code not in benchmarks:
            parsed.reject(record["_line"], f"unknown benchmark_code '{bench_code}'")
            continue
        option = (record.get("option") or "").lower()
        values = {
            "name": record["name"], "category": record["category"], "asset_class": record["asset_class"],
            "amc": record.get("amc"), "plan": record.get("plan"), "option": record.get("option"),
            "benchmark_id": benchmarks[bench_code].id if bench_code else None,
            "launch_date": record.get("launch_date"), "expense_ratio_pct": record.get("expense_ratio_pct"),
            "risk_label": record.get("risk_label"),
            "return_basis": "nav_price" if option in ("idcw", "dividend") else "nav_growth",
        }
        fund = existing.get(record["scheme_code"])
        if fund is None:
            db.add(Fund(scheme_code=record["scheme_code"], source_id=source.id,
                        is_synthetic=source.is_synthetic, **values))
            inserted += 1
            continue
        if fund.is_synthetic != source.is_synthetic:
            parsed.reject(record["_line"], "cannot change a fund between synthetic and real data")
            continue
        changed = False
        for attr, value in values.items():
            current = getattr(fund, attr)
            if isinstance(current, Decimal) and value is not None:
                same = current == Decimal(value)
            else:
                same = current == value
            if not same:
                setattr(fund, attr, value)
                changed = True
        updated += int(changed)
        unchanged += int(not changed)
    return inserted, updated, unchanged


def _existing_levels(db: Session, model, key_col, fund_ids: list, start: date, end: date):  # type: ignore[no-untyped-def]
    value_col = model.nav if model is NavObservation else model.value
    rows = db.execute(
        select(key_col, model.obs_date, value_col).where(
            key_col.in_(fund_ids), and_(model.obs_date >= start, model.obs_date <= end)
        )
    ).all()
    return rows


def _import_nav(db: Session, parsed: ParsedFile, source: DataSource, batch_id: uuid.UUID):
    resolved = _resolve_funds(db, parsed, source)
    if not resolved:
        return 0, 0, 0
    dates = [r["date"] for r, _ in resolved]
    fund_ids = list({f.id for _, f in resolved})
    window = (min(dates) - timedelta(days=10), max(dates) + timedelta(days=10))
    existing_rows = _existing_levels(db, NavObservation, NavObservation.fund_id, fund_ids, *window)
    existing = {(fid, d): (v,) for fid, d, v in existing_rows}
    code_by_id = {f.id: f.scheme_code for _, f in resolved}
    by_code: dict[str, dict[date, Decimal]] = {}
    for fid, d, v in existing_rows:
        by_code.setdefault(code_by_id[fid], {})[d] = v
    parsed.warnings += validation.flag_level_outliers(
        [r for r, _ in resolved], by_code, code_field="scheme_code", value_field="nav")
    incoming = {
        (f.id, r["date"]): {"fund_id": f.id, "obs_date": r["date"], "nav": r["nav"],
                             "source_id": source.id, "import_batch_id": batch_id}
        for r, f in resolved
    }
    to_write, ins, upd, same = _count_changes(existing, incoming, ["nav"])
    if to_write:
        _bulk_upsert(db, NavObservation, to_write, ["fund_id", "obs_date"])
    return ins, upd, same


def _import_benchmark_values(db: Session, parsed: ParsedFile, source: DataSource, batch_id: uuid.UUID):
    benchmarks = _lookup_benchmarks(db, {r["benchmark_code"] for r in parsed.records})
    resolved = []
    for record in parsed.records:
        bench = benchmarks.get(record["benchmark_code"])
        if bench is None:
            parsed.reject(record["_line"], f"unknown benchmark_code '{record['benchmark_code']}'")
        elif bench.is_synthetic != source.is_synthetic:
            parsed.reject(record["_line"], "cannot mix synthetic and real benchmark observations")
        else:
            resolved.append((record, bench))
    if not resolved:
        return 0, 0, 0
    dates = [r["date"] for r, _ in resolved]
    ids = list({b.id for _, b in resolved})
    rows = _existing_levels(db, BenchmarkObservation, BenchmarkObservation.benchmark_id, ids,
                            min(dates) - timedelta(days=10), max(dates) + timedelta(days=10))
    existing = {(bid, d): (v,) for bid, d, v in rows}
    code_by_id = {b.id: b.code for _, b in resolved}
    by_code: dict[str, dict[date, Decimal]] = {}
    for bid, d, v in rows:
        by_code.setdefault(code_by_id[bid], {})[d] = v
    parsed.warnings += validation.flag_level_outliers(
        [r for r, _ in resolved], by_code, code_field="benchmark_code", value_field="value")
    incoming = {
        (b.id, r["date"]): {"benchmark_id": b.id, "obs_date": r["date"], "value": r["value"],
                             "source_id": source.id, "import_batch_id": batch_id}
        for r, b in resolved
    }
    to_write, ins, upd, same = _count_changes(existing, incoming, ["value"])
    if to_write:
        _bulk_upsert(db, BenchmarkObservation, to_write, ["benchmark_id", "obs_date"])
    return ins, upd, same


def _dated_fund_table(model, date_col: str, value_cols: list[str]):  # type: ignore[no-untyped-def]
    """Handler factory for per-fund dated tables (AUM, SIP flows); CSV names match columns."""

    def handler(db: Session, parsed: ParsedFile, source: DataSource, _batch: uuid.UUID):
        resolved = _resolve_funds(db, parsed, source)
        if not resolved:
            return 0, 0, 0
        date_attr = getattr(model, date_col)
        keys = [(f.id, r[date_col]) for r, f in resolved]
        rows = db.execute(
            select(model.fund_id, date_attr, *[getattr(model, c) for c in value_cols])
            .where(tuple_(model.fund_id, date_attr).in_(keys))
        ).all()
        existing = {(r[0], r[1]): tuple(r[2:]) for r in rows}
        incoming = {
            (fund.id, record[date_col]): {
                "fund_id": fund.id, date_col: record[date_col], "source_id": source.id,
                **{c: record.get(c) for c in value_cols},
            }
            for record, fund in resolved
        }
        to_write, ins, upd, same = _count_changes(existing, incoming, value_cols)
        if to_write:
            _bulk_upsert(db, model, to_write, ["fund_id", date_col])
        return ins, upd, same

    return handler


def _import_holdings(db: Session, parsed: ParsedFile, source: DataSource, _batch: uuid.UUID):
    """Holdings snapshots are replaced as a whole per (fund, as-of date)."""
    resolved = _resolve_funds(db, parsed, source)
    groups: dict[tuple[int, date], list[dict]] = {}
    for record, fund in resolved:
        groups.setdefault((fund.id, record["as_of_date"]), []).append(record)
    inserted = updated = unchanged = 0
    for (fund_id, as_of), records in groups.items():
        current = db.scalars(select(FundHolding).where(FundHolding.fund_id == fund_id,
                                                       FundHolding.as_of_date == as_of)).all()
        current_set = {(h.holding_name, h.sector, h.asset_type, h.weight_pct) for h in current}
        new_set = {(r["holding_name"], r["sector"], r["asset_type"], r["weight_pct"]) for r in records}
        if current_set == new_set:
            unchanged += len(records)
            continue
        if current:
            updated += len(records)
            for holding in current:
                db.delete(holding)
            db.flush()
        else:
            inserted += len(records)
        for r in records:
            db.add(FundHolding(fund_id=fund_id, as_of_date=as_of, holding_name=r["holding_name"],
                               sector=r["sector"], asset_type=r["asset_type"], weight_pct=r["weight_pct"],
                               source_id=source.id))
    return inserted, updated, unchanged


_HANDLERS = {
    "benchmarks": _import_benchmarks,
    "funds": _import_funds,
    "nav": _import_nav,
    "benchmark_values": _import_benchmark_values,
    "aum": _dated_fund_table(FundAum, "as_of_date", ["aum_crore"]),
    "sip_flows": _dated_fund_table(FundSipFlow, "month", ["sip_inflow_crore", "sip_accounts"]),
    "holdings": _import_holdings,
}


def batch_summary(batch: ImportBatch) -> dict:
    return {
        "id": str(batch.id), "kind": batch.kind, "filename": batch.filename, "status": batch.status,
        "rows_total": batch.rows_total, "rows_inserted": batch.rows_inserted,
        "rows_updated": batch.rows_updated, "rows_unchanged": batch.rows_unchanged,
        "rows_rejected": batch.rows_rejected, "warnings": batch.warnings,
        "rejected_rows": batch.rejected_rows,
        "started_at": batch.started_at.isoformat() if batch.started_at else None,
        "finished_at": batch.finished_at.isoformat() if batch.finished_at else None,
    }
